json.id          outlet.id
json.name        outlet.name
json.email       outlet.email
json.phone       outlet.phone.to_i
json.mobile      outlet.mobile.to_i
json.address     outlet.address
json.taxs     	 outlet.taxs
json.created_at  outlet.created_at
json.updated_at  outlet.updated_at